Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authenticationuser
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: mysql